"""Initial migration with enhanced metadata fields

Revision ID: 6b538fb010b4
Revises: 
Create Date: 2025-07-31 02:14:19.724995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b538fb010b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exams_exam_external_id'), 'exams', ['exam_external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_exam_external_id'), table_name='exams')
    # ### end Alembic commands ###
